### ISSUE TITLE
Add 'touch' utility written in Rust

### ISSUE THREAD

**Issue by Venoox** [Venoox/gnu-rust-utils#3]
Add 'touch' utility written in Rust, you can only make basic functionality without flags.
If you need reference, you can find 'touch' written in C here: https://github.com/coreutils/coreutils/blob/master/src/touch.c

**Comment by devzbysiu** [comment]
I would like to take a look on that

**Comment by Venoox** [comment]
Sure, go ahead!

**Comment by devzbysiu** [comment]
Initial implementation can be found here: https://github.com/Venoox/gnu-rust-utils/pull/8

**Comment by Venoox** [comment]
Thank you for your contribution
